name: Update Docs

on:
  pull_request:
    types: [ labeled ]
  push:
    branches:
      - main

env:
  RAILS_ENV: test

jobs:
  openapi:
    if: contains(github.event.pull_request.labels.*.name, 'doc')
    name: RSpec OpenAPI
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Database
        run: |
          bundle exec rake parallel:load_schema
      - name: Run tests and update docs
        env:
          PARALLEL_TESTS_CONCURRENCY: 8
        run: bundle exec ./bin/update-docs.rb && git diff
      - name: Check for untracked changes doc
        uses: rootstrap/check_untracked_changes@v1
        with:
          path: "./doc"
